DeepSeek-R1-Qwen-1.5B:
  ZeroShot:
    timeout: 240
    max_concurrent: 256
  OneShot:
    timeout: 240
    max_concurrent: 256
  FewShot:
    timeout: 240
    max_concurrent: 256
  CoT:
    timeout: 240
    max_concurrent: 256
  SelfConsistency:
    timeout: 480
    max_concurrent: 64
  PromptGraph:
    timeout: 2400
    max_concurrent: 256

Gemma-3-4B:
  ZeroShot:
    timeout: 240
    max_concurrent: 256
  OneShot:
    timeout: 240
    max_concurrent: 256
  FewShot:
    timeout: 240
    max_concurrent: 256
  CoT:
    timeout: 240
    max_concurrent: 256
  SelfConsistency:
    timeout: 480
    max_concurrent: 64
  PromptGraph:
    timeout: 2400
    max_concurrent: 256

Qwen3-1.7B:
  ZeroShot:
    timeout: 240
    max_concurrent: 256
  OneShot:
    timeout: 240
    max_concurrent: 256
  FewShot:
    timeout: 240
    max_concurrent: 256
  CoT:
    timeout: 240
    max_concurrent: 256
  SelfConsistency:
    timeout: 480
    max_concurrent: 64
  PromptGraph:
    timeout: 2400
    max_concurrent: 256

DeepSeek-R1-0528-Qwen3-8B:
  ZeroShot:
    timeout: 240
    max_concurrent: 256
  OneShot:
    timeout: 240
    max_concurrent: 256
  FewShot:
    timeout: 240
    max_concurrent: 256
  CoT:
    timeout: 240
    max_concurrent: 256
  SelfConsistency:
    timeout: 480
    max_concurrent: 64
  PromptGraph:
    timeout: 2400
    max_concurrent: 256

medgemma-27b-it:
  ZeroShot:
    timeout: 240
    max_concurrent: 128
  OneShot:
    timeout: 240
    max_concurrent: 128
  FewShot:
    timeout: 240
    max_concurrent: 128
  CoT:
    timeout: 240
    max_concurrent: 128
  SelfConsistency:
    timeout: 480
    max_concurrent: 32
  PromptGraph:
    timeout: 2400
    max_concurrent: 128

gpt-oss-20b:
  ZeroShot:
    timeout: 240
    max_concurrent: 128
  OneShot:
    timeout: 240
    max_concurrent: 128
  FewShot:
    timeout: 240
    max_concurrent: 128
  CoT:
    timeout: 240
    max_concurrent: 128
  SelfConsistency:
    timeout: 480
    max_concurrent: 32
  PromptGraph:
    timeout: 2400
    max_concurrent: 128

gemma-3-27b-it:
  ZeroShot:
    timeout: 240
    max_concurrent: 128
  OneShot:
    timeout: 240
    max_concurrent: 128
  FewShot:
    timeout: 240
    max_concurrent: 128
  CoT:
    timeout: 240
    max_concurrent: 128
  SelfConsistency:
    timeout: 480
    max_concurrent: 32
  PromptGraph:
    timeout: 2400
    max_concurrent: 128

Mistral-Small-3.1-24B-Instruct-2503:
  ZeroShot:
    timeout: 240
    max_concurrent: 128
  OneShot:
    timeout: 240
    max_concurrent: 128
  FewShot:
    timeout: 240
    max_concurrent: 128
  CoT:
    timeout: 240
    max_concurrent: 128
  SelfConsistency:
    timeout: 480
    max_concurrent: 32
  PromptGraph:
    timeout: 2400
    max_concurrent: 128
    
Qwen2.5-72B-Instruct:
  ZeroShot:
    timeout: 240
    max_concurrent: 64
  OneShot:
    timeout: 240
    max_concurrent: 64
  FewShot:
    timeout: 240
    max_concurrent: 64
  CoT:
    timeout: 240
    max_concurrent: 64
  SelfConsistency:
    timeout: 480
    max_concurrent: 16
  PromptGraph:
    timeout: 2400
    max_concurrent: 64

Llama-3_3-Nemotron-Super-49B-v1:
  ZeroShot:
    timeout: 240
    max_concurrent: 128
  OneShot:
    timeout: 240
    max_concurrent: 128
  FewShot:
    timeout: 240
    max_concurrent: 128
  CoT:
    timeout: 240
    max_concurrent: 128
  SelfConsistency:
    timeout: 480
    max_concurrent: 32
  PromptGraph:
    timeout: 2400
    max_concurrent: 32

Llama3-Med42-70B:
  ZeroShot:
    timeout: 240
    max_concurrent: 64
  OneShot:
    timeout: 240
    max_concurrent: 64
  FewShot:
    timeout: 240
    max_concurrent: 64
  CoT:
    timeout: 240
    max_concurrent: 64
  SelfConsistency:
    timeout: 480
    max_concurrent: 16
  PromptGraph:
    timeout: 2400
    max_concurrent: 64

Llama3-OpenBioLLM-70B:
  ZeroShot:
    timeout: 240
    max_concurrent: 64
  OneShot:
    timeout: 240
    max_concurrent: 64
  FewShot:
    timeout: 240
    max_concurrent: 64
  CoT:
    timeout: 240
    max_concurrent: 64
  SelfConsistency:
    timeout: 480
    max_concurrent: 16
  PromptGraph:
    timeout: 2400
    max_concurrent: 64

gpt-oss-120b:
  ZeroShot:
    timeout: 240
    max_concurrent: 64
  OneShot:
    timeout: 240
    max_concurrent: 64
  FewShot:
    timeout: 240
    max_concurrent: 64
  CoT:
    timeout: 240
    max_concurrent: 64
  SelfConsistency:
    timeout: 480
    max_concurrent: 16
  PromptGraph:
    timeout: 2400
    max_concurrent: 64

Llama-4-Scout-17B-16E:
  ZeroShot:
    timeout: 240
    max_concurrent: 64
  OneShot:
    timeout: 240
    max_concurrent: 64
  FewShot:
    timeout: 240
    max_concurrent: 64
  CoT:
    timeout: 240
    max_concurrent: 64
  SelfConsistency:
    timeout: 480
    max_concurrent: 16
  PromptGraph:
    timeout: 2400
    max_concurrent: 64

MiniMax-M1-80k:
  ZeroShot:
    timeout: 1440
    max_concurrent: 128
  OneShot:
    timeout: 1440
    max_concurrent: 128
  FewShot:
    timeout: 1440
    max_concurrent: 128
  CoT:
    timeout: 1440
    max_concurrent: 128
  SelfConsistency:
    timeout: 2880
    max_concurrent: 32
  PromptGraph:
    timeout: 28800
    max_concurrent: 128

Qwen3-235B-A22B:
  ZeroShot:
    timeout: 1440
    max_concurrent: 128
  OneShot:
    timeout: 1440
    max_concurrent: 128
  FewShot:
    timeout: 1440
    max_concurrent: 128
  CoT:
    timeout: 1440
    max_concurrent: 128
  SelfConsistency:
    timeout: 2880
    max_concurrent: 32
  PromptGraph:
    timeout: 28800
    max_concurrent: 128

Llama-4-Maverick:
  ZeroShot:
    timeout: 1440
    max_concurrent: 128
  OneShot:
    timeout: 1440
    max_concurrent: 128
  FewShot:
    timeout: 1440
    max_concurrent: 128
  CoT:
    timeout: 1440
    max_concurrent: 128
  SelfConsistency:
    timeout: 2880
    max_concurrent: 32
  PromptGraph:
    timeout: 28800
    max_concurrent: 128

DeepSeek-R1-0528:
  ZeroShot:
    timeout: 1440
    max_concurrent: 128
  OneShot:
    timeout: 1440
    max_concurrent: 128
  FewShot:
    timeout: 1440
    max_concurrent: 128
  CoT:
    timeout: 1440
    max_concurrent: 128
  SelfConsistency:
    timeout: 2880
    max_concurrent: 32
  PromptGraph:
    timeout: 28800
    max_concurrent: 128

