DeepSeek-R1-Qwen-1.5B:
  ZeroShot:
    timeout: 240
    max_concurrent: 256
  OneShot:
    timeout: 240
    max_concurrent: 256
  FewShot:
    timeout: 240
    max_concurrent: 256
  CoT:
    timeout: 240
    max_concurrent: 256
  SelfConsistency:
    timeout: 480
    max_concurrent: 64
  PromptChain:
    timeout: 2400
    max_concurrent: 256

Llama-3.2-3B :
  ZeroShot:
    timeout: 240
    max_concurrent: 256
  OneShot:
    timeout: 240
    max_concurrent: 256
  FewShot:
    timeout: 240
    max_concurrent: 256
  CoT:
    timeout: 240
    max_concurrent: 256
  SelfConsistency:
    timeout: 480
    max_concurrent: 64
  PromptChain:
    timeout: 2400
    max_concurrent: 256

Qwen3-1.7B:
  ZeroShot:
    timeout: 240
    max_concurrent: 256
  OneShot:
    timeout: 240
    max_concurrent: 256
  FewShot:
    timeout: 240
    max_concurrent: 256
  CoT:
    timeout: 240
    max_concurrent: 256
  SelfConsistency:
    timeout: 480
    max_concurrent: 64
  PromptChain:
    timeout: 2400
    max_concurrent: 256

DeepSeek-R1-0528-Qwen3-8B:
  ZeroShot:
    timeout: 240
    max_concurrent: 256
  OneShot:
    timeout: 240
    max_concurrent: 256
  FewShot:
    timeout: 240
    max_concurrent: 256
  CoT:
    timeout: 240
    max_concurrent: 256
  SelfConsistency:
    timeout: 480
    max_concurrent: 64
  PromptChain:
    timeout: 2400
    max_concurrent: 256

medgemma-27b-it:
  ZeroShot:
    timeout: 240
    max_concurrent: 128
  OneShot:
    timeout: 240
    max_concurrent: 128
  FewShot:
    timeout: 240
    max_concurrent: 128
  CoT:
    timeout: 240
    max_concurrent: 128
  SelfConsistency:
    timeout: 480
    max_concurrent: 32
  PromptChain:
    timeout: 2400
    max_concurrent: 128

gemma-3-27b-it:
  ZeroShot:
    timeout: 240
    max_concurrent: 128
  OneShot:
    timeout: 240
    max_concurrent: 128
  FewShot:
    timeout: 240
    max_concurrent: 128
  CoT:
    timeout: 240
    max_concurrent: 128
  SelfConsistency:
    timeout: 480
    max_concurrent: 32
  PromptChain:
    timeout: 2400
    max_concurrent: 128

Mistral-Small-3.1-24B-Instruct-2503:
  ZeroShot:
    timeout: 240
    max_concurrent: 128
  OneShot:
    timeout: 240
    max_concurrent: 128
  FewShot:
    timeout: 240
    max_concurrent: 128
  CoT:
    timeout: 240
    max_concurrent: 128
  SelfConsistency:
    timeout: 480
    max_concurrent: 32
  PromptChain:
    timeout: 2400
    max_concurrent: 128
    
Qwen2.5-72B-Instruct:
  ZeroShot:
    timeout: 240
    max_concurrent: 64
  OneShot:
    timeout: 240
    max_concurrent: 64
  FewShot:
    timeout: 240
    max_concurrent: 64
  CoT:
    timeout: 240
    max_concurrent: 64
  SelfConsistency:
    timeout: 480
    max_concurrent: 16
  PromptChain:
    timeout: 2400
    max_concurrent: 64

Llama-3_3-Nemotron-Super-49B-v1:
  ZeroShot:
    timeout: 240
    max_concurrent: 128
  OneShot:
    timeout: 240
    max_concurrent: 128
  FewShot:
    timeout: 240
    max_concurrent: 128
  CoT:
    timeout: 240
    max_concurrent: 128
  SelfConsistency:
    timeout: 480
    max_concurrent: 32
  PromptChain:
    timeout: 2400
    max_concurrent: 32

Llama3-Med42-70B:
  ZeroShot:
    timeout: 240
    max_concurrent: 64
  OneShot:
    timeout: 240
    max_concurrent: 64
  FewShot:
    timeout: 240
    max_concurrent: 64
  CoT:
    timeout: 240
    max_concurrent: 64
  SelfConsistency:
    timeout: 480
    max_concurrent: 16
  PromptChain:
    timeout: 2400
    max_concurrent: 64

Llama3-OpenBioLLM-70B:
  ZeroShot:
    timeout: 240
    max_concurrent: 64
  OneShot:
    timeout: 240
    max_concurrent: 64
  FewShot:
    timeout: 240
    max_concurrent: 64
  CoT:
    timeout: 240
    max_concurrent: 64
  SelfConsistency:
    timeout: 480
    max_concurrent: 16
  PromptChain:
    timeout: 2400
    max_concurrent: 64

Llama-4-Scout-17B-16E:
  ZeroShot:
    timeout: 240
    max_concurrent: 64
  OneShot:
    timeout: 240
    max_concurrent: 64
  FewShot:
    timeout: 240
    max_concurrent: 64
  CoT:
    timeout: 240
    max_concurrent: 64
  SelfConsistency:
    timeout: 480
    max_concurrent: 16
  PromptChain:
    timeout: 2400
    max_concurrent: 64

MiniMax-M1-80k:
  ZeroShot:
    timeout: 360
    max_concurrent: 32
  OneShot:
    timeout: 360
    max_concurrent: 32
  FewShot:
    timeout: 360
    max_concurrent: 32
  CoT:
    timeout: 360
    max_concurrent: 32
  SelfConsistency:
    timeout: 720
    max_concurrent: 8
  PromptChain:
    timeout: 3600
    max_concurrent: 32

Qwen3-235B-A22B:
  ZeroShot:
    timeout: 360
    max_concurrent: 32
  OneShot:
    timeout: 360
    max_concurrent: 32
  FewShot:
    timeout: 360
    max_concurrent: 32
  CoT:
    timeout: 360
    max_concurrent: 32
  SelfConsistency:
    timeout: 720
    max_concurrent: 8
  PromptChain:
    timeout: 3600
    max_concurrent: 32

DeepSeek-R1-0528:
  ZeroShot:
    timeout: 360
    max_concurrent: 32
  OneShot:
    timeout: 360
    max_concurrent: 32
  FewShot:
    timeout: 360
    max_concurrent: 32
  CoT:
    timeout: 360
    max_concurrent: 32
  SelfConsistency:
    timeout: 720
    max_concurrent: 8
  PromptChain:
    timeout: 3600
    max_concurrent: 32

